name: KnockbackFFA
main: KnockbackFFA\KnockbackFFA
version: 1.8.0
api: 3.0.0-ALPHA10
author: McpeBooster
website: twitter.com/McpeBooster
commands:
  knockbackffa:
    description: Join KnockbackFFA directly per Command
  kbf:
    description: Join KnockbackFFA directly per Command
