name: BoostPad
main: BoxOfDevs\BPad\Main
api:
- 2.0.0
- 3.0.0
- 3.0.0-Alpha9
- 3.0.0-ALPHA10
- 3.0.0-ALPHA11
- 3.0.0-ALPHA12
- 3.0.0-ALPHA13
- 3.0.0-ALPHA14
- 3.0.0-ALPHA15
version: 1.0
author: BoxOfDevs Team
